#!/usr/bin/env bash
# NSR scaffold: create OR convert a project to the WayOfNorthStar layout.
# Fully self-contained — copies templates from THIS skill's assets/ and gates the result.
#
# Usage:
#   scaffold.sh /path/to/project --name "MyProject" [--description "What it does"] [--force]
#
# - Creates the full NSR tree (root routing files, RULES/, docs/, .agents/skills/, .compliance/).
# - Never overwrites existing files unless --force is passed.
# - Substitutes __PROJECT__ / __DESCRIPTION__ / __project__ in templates.
# - Post-condition: runs validate.sh and requires it to pass.
set -e

SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ASSETS="$SKILL_DIR/assets"

PROJECT_DIR=""
PROJECT_NAME=""
PROJECT_DESCRIPTION="__DESCRIPTION__"
FORCE=0

usage() {
  echo "Usage: scaffold.sh <dir> --name <ProjectName> [--description <text>] [--force]"
  exit 1
}

# --- parse args ---
while [ $# -gt 0 ]; do
  case "$1" in
    --name) PROJECT_NAME="$2"; shift 2 ;;
    --description) PROJECT_DESCRIPTION="$2"; shift 2 ;;
    --force) FORCE=1; shift ;;
    -h|--help) usage ;;
    -*) echo "Unknown option: $1"; usage ;;
    *) PROJECT_DIR="$1"; shift ;;
  esac
done

[ -n "$PROJECT_DIR" ] && [ -n "$PROJECT_NAME" ] || usage

# slug for env templates (lowercase, hyphenated)
SLUG=$(printf '%s' "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | tr ' _' '-')

mkdir -p "$PROJECT_DIR"
cd "$PROJECT_DIR"
DEST_ROOT="$(pwd)"

echo "[nsr] scaffolding $PROJECT_NAME -> $DEST_ROOT"

copy_tree() {
  local src="$1"; local dst="$2"
  mkdir -p "$dst"
  for item in "$src"/*; do
    [ -e "$item" ] || continue
    local base; base="$(basename "$item")"
    if [ -d "$item" ]; then
      copy_tree "$item" "$dst/$base"
    else
      local target="$dst/$base"
      if [ -e "$target" ] && [ "$FORCE" -eq 0 ]; then
        echo "[nsr] SKIP (exists): $target"
        continue
      fi
      # placeholder substitution
      sed -e "s|__PROJECT__|$PROJECT_NAME|g" \
          -e "s|__DESCRIPTION__|$PROJECT_DESCRIPTION|g" \
          -e "s|__project__|$SLUG|g" \
          "$item" > "$target"
      echo "[nsr] wrote: $target"
    fi
  done
}

echo "[nsr] root routing files + RULES/"
copy_tree "$ASSETS/root" "$DEST_ROOT"
copy_tree "$ASSETS/RULES" "$DEST_ROOT/RULES"

echo "[nsr] docs/ tree"
copy_tree "$ASSETS/docs" "$DEST_ROOT/docs"

echo "[nsr] .agents/skills/ tree"
copy_tree "$ASSETS/agents_skills" "$DEST_ROOT/.agents/skills"

echo "[nsr] .compliance/ tree (generated by the self-contained compliance skill)"
if [ -f "$DEST_ROOT/.agents/skills/NSRcompliance/generate.sh" ]; then
  bash "$DEST_ROOT/.agents/skills/NSRcompliance/generate.sh" "$DEST_ROOT" --force
else
  echo "[nsr] (fallback) stamping from assets/compliance"
  copy_tree "$ASSETS/compliance" "$DEST_ROOT/.compliance"
fi

# make scripts executable
find "$DEST_ROOT/.agents/skills" -name "*.sh" -type f -exec chmod u+x {} + 2>/dev/null || true
find "$DEST_ROOT/.compliance" -name "*.sh" -type f -exec chmod u+x {} + 2>/dev/null || true
chmod +x "$DEST_ROOT/docs/CI_CD/deployment/deploy.sh" 2>/dev/null || true

echo "[nsr] running validation"
"$SKILL_DIR/scripts/validate.sh" "$DEST_ROOT"

echo "[nsr] DONE: $PROJECT_NAME scaffolded at $DEST_ROOT"
echo "[nsr] next: git init, fill TECH_STACK.md/FEATURES.md, add features under .agents/skills/features/"

exit 0